import type { AppProps } from 'next/app'
import { ThemeProvider } from "styled-components";
import { GlobalStyle } from "@/theme/global-style";
import { defaultTheme } from "@/theme/default-theme";
import { appWithTranslation } from "next-i18next";
import Head from "next/head";
import { AppWrapper } from "../context/app-context";
import { ParallaxProvider } from "react-scroll-parallax";

function App({ Component, pageProps }: AppProps) {

    return <>
        <Head>
            <title>Przemysław Saja</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>
        <ParallaxProvider>
            <ThemeProvider theme={ defaultTheme }>
                <GlobalStyle/>
                <AppWrapper>
                    <Component { ...pageProps } />
                </AppWrapper>
            </ThemeProvider>
        </ParallaxProvider>
    </>
}

export default appWithTranslation(App)
